with cte_gdfs as
(
SELECT *
FROM "ZSEZ_TF_HR105_GDFS"
( P_KEYDATE => TO_VARCHAR(CURRENT_DATE,'YYYYMMDD') , P_EMPLSTATUS => '*', P_EMPLGRP => '*', P_COMP_CODE => '*' )
)
,
cte_user_not_in_hr as
(
SELECT G.*,U.PERSONNUMBER, U.USERNAME, COALESCE(G.EMPLOYEE,'X') AS IS_NOT_IN_HR
FROM RVPUSER AS U
LEFT OUTER JOIN cte_gdfs as G
ON G.MANDT = U.MANDT AND G.USRID = U.USERNAME AND U.PERSONNUMBER = G.EMPLOYEE
)
SELECT DISTINCT PERSONNUMBER AS EMPLOYEE,  USERNAME, IS_NOT_IN_HR
FROM cte_user_not_in_hr
/*WHERE IS_NOT_IN_HR = 'X'*/

